config/routes.rb
Rails.application.routes.draw do

  root to: "contact#index"

  get 'contact/index'

  get 'contact/new'

  post 'contact/create'

  get 'contact/add_address', to: 'contact#add_address'

  get 'contact/add_communication', to: 'contact#add_communication'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact
end

app/models/communication.rb
class Communication < ActiveRecord::Base
  belongs_to :contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :addresses, dependent: :destroy
  has_many :communications, dependent: :destroy
  accepts_nested_attributes_for :addresses, :communications, reject_if: :all_blank

  def self.address_build
    contact = self.new
    contact.addresses.build
    contact
  end

  def self.communication_build
    contact = self.new
    contact.communications.build
    contact
  end

  def full_name
    check_full_name = self.first_name.capitalize + ' ' + self.last_name.capitalize
    check_full_name.present? ? check_full_name : '-'
  end

  def primary_address
    first_address = self.addresses.first.try(:address)
    first_country = self.addresses.first.try(:country).try(:capitalize)
    check_primary_address = [first_address, first_country].compact.reject { |i| i.size.zero? }.join(' - ')
    check_primary_address.present? ? check_primary_address : '-'
  end

  def primary_phone
    check_primary_phone = self.communications.first.try(:phone)
    check_primary_phone.present? ? check_primary_phone : '-'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
    @contact.addresses.build
    @contact.communications.build
    @address_count = 1
    @communication_count = 1
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:info] = 'Contact was successfully created.'
      redirect_to root_path
    else
      render :new
    end
  end

  def add_address
    @contact = Contact.address_build
    @address_count = params[:address_count]
    render :add_address, layout: false
  end

  def add_communication
    @contact = Contact.communication_build
    @communication_count = params[:communication_count]
    render :add_communication, layout: false
  end

  private
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, addresses_attributes: [ :id, :address, :country ], communications_attributes: [ :id, :phone ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/_address_fields.html.haml
= contact_field.fields_for :addresses, child_index: child_index do |address_field|
  = address_field.input :address, label: "Address #{address_count}", input_html: { class: 'address-count'}
  = address_field.input :country, label: "Country #{address_count}", as: :string

app/views/contact/_communication_fields.html.haml
= contact_field.fields_for :communications, child_index: child_index do |communication_field|
  = communication_field.input :phone, label: "Phone #{communication_count}", input_html: { class: 'communication-count'}

app/views/contact/add_address.html.haml
= simple_form_for @contact, url: contact_create_path do |contact_field|
  #add_address_fields
    = render partial: "address_fields", locals: { contact_field: contact_field, child_index: Time.now.to_i, address_count: @address_count }

app/views/contact/add_communication.html.haml
= simple_form_for @contact, url: contact_create_path do |contact_field|
  #add_communications_fields
    = render partial: "communication_fields", locals: { contact_field: contact_field, child_index: Time.now.to_i, communication_count: @communication_count }

app/views/contact/create.html.haml
%h1 Contact#create
%p Find me in app/views/contact/create.html.erb

app/views/contact/index.html.haml
.clearfix
%h2.center Contact Lists
.space-4
.clearfix
.table-responsive.clearfix
  .space-4
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Email Id
        %th Primary Address
        %th Primary Phone
    %tbody
      - if @contacts.empty?
        %tr
          %td.center{colspan: "4"}
            No records found!
      - @contacts.each do |contact|
        %tr
          %td= contact.full_name
          %td= contact.email.present? ? contact.email : '-'
          %td= contact.primary_address
          %td= contact.primary_phone

app/views/contact/new.html.haml
.clearfix
%h2.center New Contact
.clearfix
.row
  .col-xs-offset-3.col-xs-5
    = simple_form_for @contact, url: contact_create_path, html: {class: "form-horizontal", method: :post} do |contact_field|
      = contact_field.input :first_name
      = contact_field.input :last_name
      = contact_field.input :email
      .row.well
        .col-xs-12
          %ul.nav.nav-pills
            %li.active
              %a{"data-target" => "#address", "data-toggle" => "tab", href: "#address"} Address(s)
            %li
              %a{"data-target" => "#communication", "data-toggle" => "tab", href: "#communication"} Communication Details
          .tab-content
            #address.tab-pane.active.fade.in
              #add_address_fields
                = render partial: "address_fields", locals: { contact_field: contact_field, child_index: Time.now.to_i, address_count: @address_count }
              .pull-right
                = link_to "Add another address", "#", id: "add_address", class: 'btn btn-success btn-sm'
            #communication.tab-pane
              #add_communications_fields
                = render partial: "communication_fields", locals: { contact_field: contact_field, child_index: Time.now.to_i, communication_count: @communication_count }
              .pull-right
                = link_to "Add another phone", "#", id: :add_communication, class: 'btn btn-success btn-sm'
      .clearfix
      .center
        = link_to "Cancel", root_path, class: 'btn btn-danger btn-sm'
        = contact_field.button :submit, class: 'btn btn-success btn-sm'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TestProject
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .main-content
      .main-content-inner
        .container-fluid
          .row-fluid
            .row.well
              .col-xs-10
                .pull-right
                  = link_to "All Contact", root_path, class: 'btn btn-success btn-sm'
                  = link_to "New Contact", contact_new_path, class: 'btn btn-success btn-sm'
              .clearfix
              .space-4
              - flash.each do |key, value|
                - key = 'info' if ['notice','alert'].include?(key)
                .alert.fade.in.center{class: "alert-#{key}"}
                  %button.close{"data-dismiss" => "alert"} x
                  = raw(value)
              = yield
            .clearfix